#!/bin/bash

#PBS -V 
#PBS -l walltime=24:00:00
#PBS -m a
#PBS -A ren-group

# properties = {"params": {}, "input": ["bam/test.filt.nodup.srt.bam"], "wildcards": ["test"], "output": ["bigWig/test.filt.nodup.srt.bw", "bigWig/test.filt.nodup.srt.gs"], "jobid": 1, "threads": 1, "cluster": {}, "local": false, "log": [], "rule": "bam2bw", "resources": {}}
#module load biotools
module load R
module load python
module load bwa
module load samtools
module load bedtools
#module switch samtools/1.2 samtools/1.3
unset PYTHONPATH
source /home/shz254/py34env/bin/activate
export R_LIBS=/home/shz254/R_LIB:$R_LIBS
cd /home/huh025/chip-seq-pipeline/example && \
/home/shz254/py34env/bin/python3.4 -m snakemake bigWig/test.filt.nodup.srt.bw bigWig/test.filt.nodup.srt.gs --snakefile /home/huh025/chip-seq-pipeline/bin/Snakefile \
--force -j --keep-target-files --keep-shadow --keep-remote \
--wait-for-files bam/test.filt.nodup.srt.bam /home/huh025/chip-seq-pipeline/example/.snakemake/tmp.pgjl33uy --latency-wait 5 \
--benchmark-repeats 1 \
--force-use-threads --wrapper-prefix https://bitbucket.org/snakemake/snakemake-wrappers/raw/ \
 --config GENOME=hg19 BWA_INDEX_PATH=/oasis/tscc/scratch/bil022/HiC/ref/ -p --nocolor \
--notemp --quiet --no-hooks --nolock --printshellcmds  --force-use-threads  --allowed-rules bam2bw  && touch "/home/huh025/chip-seq-pipeline/example/.snakemake/tmp.pgjl33uy/1.jobfinished" || (touch "/home/huh025/chip-seq-pipeline/example/.snakemake/tmp.pgjl33uy/1.jobfailed"; exit 1)


